config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    
  }
  # Looks like /blogs/1/comments/edit/:id
  resources :blogs do
    resources :comments
  end
  
  # Looks like /comments/1/comments/edit/:id
  resources :comments do
    resources :comments
  end
  
  get 'history', to: 'comments#history'

  root "blogs#index"
  get "/confirmation_pending" => "static_pages#after_registration_path"

  # Follower System
  get "/profiles/:id", to: "profiles#show", as: "profile"
  
  post "profiles/follow", to: "profiles#follow"
  delete "profiles/unfollow", to: "profiles#unfollow"
  get "/profiles", to: "profiles#index"

  resources :likes, only: [:create, :destroy]
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  # has_one_attached :photo

  # To Resize the image
  has_one_attached :photo do |attachable|
    attachable.variant :thumb, resize_to_limit: [350, 350]
  end

  # Thumbnail Image
  has_one_attached :thumbnail do |attachable|
    attachable.variant :thumb, resize_to_limit: [350, 350]
  end

  # Pagination
  paginates_per 10

  belongs_to :category

  # Action Text for Blog Body
  has_rich_text :blog_body

  # Like Feature
  has_many :likes
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  load_and_authorize_resource
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  add_breadcrumb "RuClicks", :root_path

  def index
    @query = Blog.ransack(params[:q])
    @blogs = @query.result(distinct: true).order("created_at DESC")
    if params[:category].blank?
      @blogs = Blog.all.page(params[:page]).order("created_at DESC")
    else
      @category_id = Category.find_by(category: params[:category]).id
      @blogs = Blog.where(category_id: @category_id).page(params[:page]).order("created_at DESC")
    end
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)
    @blog.user = current_user
    if @blog.save
      flash[:notice] = "Blog Created Succesfully"
      redirect_to blogs_path
    else
      flash[:errors] = @blog.errors.full_messages
      redirect_to new_blog_path
    end
  end

  def show
    # Breadcrumb Navbar
    add_breadcrumb "#{@blog.category.category}", blogs_path, title: "Back to the Home"
    add_breadcrumb "#{@blog.title}", blog_path(@blog)
    # Views Update
    views = @blog.views + 1
    @blog.update(views: views)
    @comments = @blog.comments.order("created_at DESC")
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      flash[:notice] = "Blog Updated Successfully"
      redirect_to blog_path(@blog)
    else
      flash[:errors] = @blog.errors.full_messages
      redirect_to edit_blog_path
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "Blog was successfully destroyed."
  end

  def history
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :subtitle, :photo, :thumbnail, :category_id, :blog_body)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="center flex-column form h-auto mt-3">
  <div class="card shadow" style="width: 36rem;">
    <div class="card-header">
      <h2 class="text-center mt-2">Blog Form</h2>
    </div>
    <div class="card-body">
      <!--Error Message-->
      <% if flash[:errors] %>
        <% flash[:errors].each do |error| %>
          <p class="text-danger"><%= error %></p>
        <% end %>
      <% end %>
      <!-- Form Started Here -->
      <%= form_with model: @blog do |f| %>
        <%#= f.hidden_field :user_id, :value => current_user.id %>
        <br>
        <%= f.label :category, "Category :", class:"mt-3" %>
        <%= f.select :category_id, Category.all.map { |c| [c.category, c.id]} %>
        <br>
        <%= f.label :title, "Blog Title :", class:"mt-3" %>
        <%= f.text_field :title, placeholder: "Enter Title Here", class:"mb-2 form-control" %>
        <br>
        <%= f.label :subtitle, "Subtitle :" %>
        <%= f.text_field :subtitle, placeholder: "Enter Subtitle Here", class:"mb-2 form-control" %>
        <br>
        <%= f.label :blog_body, "Action Body :" %>
        <%= f.rich_text_area :blog_body, rows: 10, placeholder: "Enter Your Main Content Here", class:"mb-2 form-control" %>
        <br>
        <%= f.label :photo, "Photo :" %>
        <%= f.file_field :photo, class:"mb-2 form-control" %>
        <br>
        <%= f.label :thumbnail, "Thumbnail :" %>
        <%= f.file_field :thumbnail, class:"mb-2 form-control" %>
        <br>
        <div class="d-flex justify-content-center">
          <%= f.submit "Save Blog", class:"btn-secondary border-0 shadow py-2 px-5" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/blogs/edit.html.erb
<!-- Edit Blog Form -->
<%= render 'form' %>

app/views/blogs/index.html.erb
<div class="container mt-4">
  <div class="d-inline d-flex justify-content-around align-items-center category-nav">
    <% Category.all.each do |category| %>
      <%= link_to category.category, blogs_path(category: category.category), class:"text-decoration-none text-dark" %>
    <% end %>
  </div>
  <hr class="mt-2 mb-5">
  <% @blogs.each do |blog| %>
    <div class="p-md-5 mb-4 rounded border">
      <div class="col-12 px-0 d-flex align-items-center justify-content-between">
        <div>
          <h1 class="display-4 fst-italic blog-title"><%= link_to blog.title, blog_path(blog) %></h1>
          <p class="badge bg-danger"> <%= blog.category.category %> </p>
          <p class="lead my-3"><%= blog.blog_body.to_plain_text.truncate_words(30) %></p>
          <div class="text-muted mb-1">
            <%= blog.updated_at.strftime("%A, %B %e, %Y") %> by 
            <%= blog.user.username %> <br>
            <%= pluralize(blog.views, "View") %> || <%= pluralize(blog.likes.count, "Like") %>
          </div>
          <div class="d-flex">
            <% if can? :update, blog %>
              <%= button_to "Edit" , edit_blog_path(blog), method: :get ,class:"btn btn-outline-success shadow px-3 py-2" %>
            <% end %>
            <% if can? :destroy, blog %>
              <%= button_to "Delete", blog_path(blog), method: :delete ,class:"btn btn-outline-danger shadow ms-2 px-3 py-2" %>
            <% end %>
          </div>
        </div>
        <div class="d-none d-lg-block">
          <% if blog.thumbnail.attached? %>
            <%= image_tag blog.thumbnail, alt: "Image not loaded", class: "img-fluid"  %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<!-- New Blog Form -->
<%= render 'form' %>

app/views/blogs/show.html.erb
<!-- Blog Details Showing -->
<div class="container mt-4">
  <div class="breadcrumb">
    <%= render_breadcrumbs %>
  </div>
  <hr class="mt-2 mb-5">
  <div class="row g-5 mb-4">
    <div class="col-12">
      <article>
        <div class="d-flex justify-content-between">
          <h2><%= @blog.title %></h2>
          <div class="d-flex">
            <% if can? :update, @blog %>
              <%= button_to "Edit" , edit_blog_path, method: :get ,class:"btn btn-outline-success shadow px-5 py-2" %>
            <% end %>
            <% if can? :destroy, @blog %>
              <%= button_to "Delete", blog_path(@blog), method: :delete ,class:"btn btn-outline-danger shadow px-5 py-2 ms-2" %>
            <% end %>
          </div>
        </div>
        <p class="badge bg-danger"> <%= @blog.category.category %> </p>
        <br>
        <div class="d-flex justify-content-between">
          <p>
            <%= @blog.updated_at.strftime("%A, %B %e, %Y") %> by 
            <%= link_to "#{@blog.user.username}", profile_path(@blog.user.id), class:"fw-bold p-1 text-danger blog-creator" %> <br>
            <%= pluralize(@blog.views, "View") %> || <%= pluralize(@blog.likes.count, "Like") %> <br>
            <strong> <%= @blog.subtitle %> </strong>
          </p>
          <% if can? :create, Like %>
            <div class="like-div mb-4">
              <% like = current_user.likes.find_by(blog: @blog) %>
              <% if like.nil? %>
                <!-- Like Implementation using button_to RAILS -->
                <%#= button_to "Like-2", likes_path, method: :post, params: { like: { blog_id: @blog.id }} %>
                <!-- Like Implementation using HTML FORM -->
                <form action="/likes" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
                  <input type="hidden" name="like[blog_id]" value="<%= @blog.id %>">
                  <input type="submit" value="Like" class="btn btn-danger rounded px-3">
                </form>
              <% else %>
                <!-- Unlike Implementation using button_to RAILS -->
                <%#= button_to "Unike-2", like_path(like), method: :delete %>
                <!-- Unlike Implementation using HTML FORM -->
                <form action="<%= like_path(like) %>" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="submit" value="Unlike" class="btn btn-warning shadow rounded px-3">
                </form>
              <% end %>
            </div>
          <% end %>
        </div>
        <hr>
        <% if @blog.photo.attached? %>
          <%= image_tag @blog.photo, alt:"Image Not Loaded", class:"img-fluid" %>
        <% end %>
        <p><%= @blog.blog_body %></p>
      </article>
    </div>
  </div>
  <!-- Comment Section Start Here -->
  <% if can? :create, Comment %>
    <%= render 'comments/form', commentable: @blog, local: Comment.new %>
  <% end %>
  <div id="comment-pane">
    <% @comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </div>
  <!-- Recent Posts Div Start Here -->
  <div class="recent-blogs mt-5">
    <h3 class="bg-danger text-light p-2"> Recent Blogs </h3>
    <div class="row">
      <% Blog.last(4).each do |recent_blog| %>
        <div class="col-lg-6 col-md-12 col-sm-12">
          <a href="/blogs/<%=recent_blog.id%>">
            <div class="card mb-3">
              <div class="row g-0">
                <div class="col-md-4 text-center">
                  <%= image_tag recent_blog.thumbnail, alt:"Image Not Loaded", class:"img-fluid rounded-start" %>
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><%= recent_blog.title %></h5>
                    <p class="card-text"><%= recent_blog.blog_body.to_plain_text.truncate_words(20) %></p>
                    <small class="card-text text-muted">
                      <p>
                        <%= recent_blog.updated_at.strftime("%A, %B %e, %Y") %> by 
                        <%= recent_blog.user.username %> <br>
                        <%= pluralize(recent_blog.views, "View") %> || <%= pluralize(recent_blog.likes.count, "Like") %> <br>
                      </p>
                    </small>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
  <!-- From Author Div Start Here -->
  <div class="blogs-from-author mt-5">
    <h3 class="bg-danger text-light p-2"> Blogs From This Author </h3>
    <div class="row">
      <% Blog.where(user_id: @blog.user.id).last(4).each do |blogs_from_author| %>
        <div class="col-lg-6 col-md-12 col-sm-12">
          <a href="/blogs/<%=blogs_from_author.id%>">
            <div class="card mb-3">
              <div class="row g-0">
                <div class="col-md-4 text-center">
                  <%= image_tag blogs_from_author.thumbnail, alt:"Image Not Loaded", class:"img-fluid rounded-start" %>
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <h5 class="card-title"><%= blogs_from_author.title %></h5>
                    <p class="card-text"><%= blogs_from_author.blog_body.to_plain_text.truncate_words(20) %></p>
                    <small class="card-text text-muted">
                      <p>
                        <%= blogs_from_author.updated_at.strftime("%A, %B %e, %Y") %> by 
                        <%= blogs_from_author.user.username %> <br>
                        <%= pluralize(blogs_from_author.views, "View") %> || <%= pluralize(blogs_from_author.likes.count, "Like") %> <br>
                      </p>
                    </small>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>