config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    
  }
  # Looks like /blogs/1/comments/edit/:id
  resources :blogs do
    resources :comments
  end
  
  # Looks like /comments/1/comments/edit/:id
  resources :comments do
    resources :comments
  end
  
  get 'history', to: 'comments#history'

  root "blogs#index"
  get "/confirmation_pending" => "static_pages#after_registration_path"

  # Follower System
  get "/profiles/:id", to: "profiles#show", as: "profile"
  
  post "profiles/follow", to: "profiles#follow"
  delete "profiles/unfollow", to: "profiles#unfollow"
  get "/profiles", to: "profiles#index"

  resources :likes, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  before_create :set_comment_number

  # Polymorphic Comments
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  private

  def set_comment_number
    self.comment_number = user.comment_created
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable, only: [:create]
  before_action :set_comment, except: [:create]
  before_action :authenticate_user!

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    @comment.reply = true if params[:comment_id]
    @comment.save
    render :json => @comment.comments
  end

  def edit
  end

  def update
    # To Store Comment History
    if @comment.edit_history == ""
      @comment.edit_history = "Original: " + @comment.comment_body + "\n"
    else
      @comment.edit_history = @comment.edit_history + "Edit: " + params[:comment][:comment_body] + "\n"
    end
    @comment.update(comment_params)
    render :json => @comment
    # render :json => @comment.comments
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_body)
  end

  def find_commentable
    # Comment
    if params[:comment_id]
      @commentable = Comment.find_by_id(params[:comment_id])
    elsif params[:blog_id]
      # Blog
      @commentable = Blog.find(params[:blog_id])
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-container" id="comment-<%= comment.id %>">
  <div class="container">
    <%= render 'comments/comments', comment: comment, local: Comment.new %>
    <% unless comment.reply %>
      <div class="row">
        <div class="col-3"></div>
        <div class="col-9">
          <% if can? :create, Comment %>
            <div class="comment-form-nested">
              <%= render 'comments/form', commentable: comment, local: Comment.new %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-2 d-flex flex-column align-items-center">
    <div class="row">
      <%= image_tag("user1.png", class:"comment-avatar mt-2", style:"width: 160px;") %>
    </div>
    <div class="row">
      <div class="comment-timestamp" id="edit-history-text-<%= comment.id%>">
        <%= render 'comments/edit_history_text', comment: comment%>
      </div>
    </div>
  </div>
  <div class="col-10">
    <div class="row mt-2">
      <div class="col-8">
        <div class="comment-username mt-2 fw-bold">
          <%= comment.user.username%>
        </div>
        <div class="comment-number fw-light">
          Comment #<%= comment.comment_number%>
        </div>
      </div>
      <% if current_user && (current_user == comment.user)%>
        <div class="col-4 mt-2 text-center">
          <div class="button-group" role="group" aria-label="Edit and Delete Button Group">
            <%= link_to "Edit", edit_comment_path(comment), class: 'btn btn-warning', remote: true %>
            <%= link_to "Delete", comment, class:'btn btn-danger', method: :delete, remote: true %>
          </div>
        </div>
      <% end %>
    </div>
    <hr>
    <div class="comment-body" id="comment-body-<%= comment.id %>">
      <%= comment.comment_body %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-2"></div>
  <div class="col-10">
    <div class="inner-comment-container" id="reply-<%=comment.id%>">
      <% comment.comments.each do |comment|%>
        <%= render comment %>
      <% end %>
    </div>
  </div>
</div>
<!-- Modal-->
<div class="modal fade" id="edit_history" tabindex="-1" role="dialog" aria-labelledby="Comment Edit History" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="edit_history_title">Edit History</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="edit-history-body">
        <%= render 'comments/edit_history', comment: comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/_edit_history.html.erb
<%= comment.edit_history.gsub(/\n/, '<br><hr>').html_safe %>

app/views/comments/_edit_history_text.html.erb
<%= time_ago_in_words(comment.created_at) %> ago
<br>
<% edit_history = comment.edit_history == "" ? "" : "Last edited " + time_ago_in_words(comment.updated_at) + " ago" %>
<%= link_to(edit_history, 'javascript:;', data: {toggle: "modal", target: "#edit_history"}) %>

app/views/comments/_form.html.erb
<div class="row">
  <div class="comment-form">
    <%= form_with model: [commentable, local] do |f| %>
      <div class="form-group d-flex align-items-center">
        <%= f.text_area :comment_body, placeholder:"Add Your Comments...", class:"reply-form-#{commentable.id} form-control", id: f.object.object_id, method: :patch %>
        <%= f.submit "Add", class:"btn btn-secondary ms-2 px-3 py-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/create.js.erb
if ("<%= @comment.reply %>" === 'true') {
  var comment_pane;
  
  if("<%= @commentable.comments.count %>" === "0") {
    comment_pane = "#reply-container-<%= @commentable.id %>";
  } else {
    comment_pane = "#reply-<%= @comment.commentable.id %>";
  }

  $(comment_pane).append(" <%= j render @comment %>");
  $(".reply-form-<%= @commentable.id %>").val('');
} else {
  $("#comment-pane").prepend("<%= j render @comment %>");
  $(".reply-form-<%= @commentable.id %>").val('');
}

app/views/comments/destroy.js.erb
$("comment-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= j render 'comments/form', commentable: @comment.commentable, local: @comment %>")

app/views/comments/update.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= raw @comment.body.body.to_html() %>");

$("#edit-history-body").html("<%= j render 'comments/edit_history', comment: @comment %>");

$("#edit-history-text-<%= @comment.id %>").html("<%= j render 'comments/edit_history_text', comment: @comment %>");