config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks",
    
  }
  # Looks like /blogs/1/comments/edit/:id
  resources :blogs do
    resources :comments
  end
  
  # Looks like /comments/1/comments/edit/:id
  resources :comments do
    resources :comments
  end
  
  get 'history', to: 'comments#history'

  root "blogs#index"
  get "/confirmation_pending" => "static_pages#after_registration_path"

  # Follower System
  get "/profiles/:id", to: "profiles#show", as: "profile"
  
  post "profiles/follow", to: "profiles#follow"
  delete "profiles/unfollow", to: "profiles#unfollow"
  get "/profiles", to: "profiles#index"

  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
  <div class="container-fluid">
    <a href="/" class="me-5 logo">RuClicks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active " aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active " aria-current="page" href="#">About</a>
        </li>
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Contact
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Mail</a></li>
            <li><a class="dropdown-item" href="#">Call</a></li>
          </ul>
        </li>
      </ul>
      <div class="d-flex">
        <% if signed_in? %>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown ">
              <a class="btn dropdown-toggle active btn-warning" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "New Blog", new_blog_path, class:"dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Profile", profiles_path, class:"dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li> <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: "false" }, class:"dropdown-item" %> </li>
              </ul>
            </li>
          </ul>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class:"btn btn-success border-0 rounded-pill shadow px-3 py-2 text-decoration-none" %>
          <%= link_to "Register", new_user_registration_path, class:"btn btn-primary border-0 rounded-pill shadow px-3 py-2 ms-2 text-decoration-none" %>
        <% end %>
      </div>
      <div class="search-form d-flex align-items-center">
        <%= search_form_for(@query, url: blogs_path, method: :get, class:"d-flex ms-2") do |f| %>
          <%= f.search_field :title_or_subtitle_i_cont_any, placeholder: "Search Blogs...", class: "form-control me-2" %>
          <%= f.submit "Search", class: "btn btn-outline-light" %>
        <% end %>
        <%= button_to "Clear", blogs_path, method: :get, class: "btn btn-outline-dark ms-1" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RuClicks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--Bootstrap CDN  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <% if notice %>
      <div class="alert alert-success text-center alert-dismissible fade show role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger text-center alert-dismissible fade show role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>